### ISSUE TITLE
Simpler data lookups

### ISSUE THREAD

**Issue by TWiStErRob** [minddust/minddust.github.io#5]
Re: http://www.minddust.com/post/tags-and-categories-on-github-pages/

It's possible to get rid of this double for lookup:
```
{% for post_tag in post.tags %}
    {% for data_tag in site.data.tags %}
        {% if data_tag.slug == post_tag %}
            {% assign tag = data_tag %}
        {% endif %}
    {% endfor %}
```

Instead you could write a much nicer:
```
{% for post_tag in post.tags %}
    {% assign tag = site.data.tags[post_tag] %}
```

Your `tags.yml` currently looks like this:
```
- slug: django
  name: Django

- slug: django-template-tags
  name: Django Template Tags

- slug: font-awesome
  name: Font Awesome

- slug: icons
  name: Icons
```

and the above works if you restructure it like so:
```
django:
  slug: django
  name: Django
django-template-tags:
  slug: django-template-tags
  name: Django Template Tags
font-awesome:
  slug: font-awesome
  name: Font Awesome
icons:
  slug: icons
  name: Icons
```
with the added benefit of `{{site.data.tags.icons.name}}`, should you want to do that. It makes more sense if you're crossreferencing projects. The dot notation even works with `font-awesome`, probably because Liquid is not a full-fledged language and `-` doesn't mean minus.

and since you only used slug to look the tag up, you it's not needed any more:
```
django:
  name: Django
django-template-tags:
  name: Django Template Tags
font-awesome:
  name: Font Awesome
icons:
  name: Icons
```

Regarding `/blog/tag/{{ tag.slug }}/", since `tag.slug == post_tag`, was true you can use that to create the url. This is really question of taste though, if you don't mind duplicating the slug as tag key in yaml you could use the uniform post.slug version.

When you're listing all tags you can use
```
{% for data_tag_entry in site.data.tags %}
    {% assign data_tag_slug = data_tag_entry[0] %}
    {% assign data_tag = data_tag_entry[1] %}
```
so the slug is not lost.

This obviosly works for all data ymls.
